project:
  type: book

book:
  title: "Measurement, Abstraction, and Information in the Natural World"
  subtitle: "Multi-part Quarto/R structure"
  author: "Prometheus"
  chapters:
    - index.qmd
    - frontmatter/how-to-read.qmd
    - part: "Slothful Apex"
      chapters:
        - source/part-1/book-1/chapter-1.qmd
        - source/part-1/book-1/chapter-2.qmd
        - source/part-1/book-2/chapter-1.qmd
        - source/part-1/book-2/chapter-2.qmd
    - part: "Avid Wanderlust"
      chapters:
        - source/part-2/book-1/chapter-1.qmd
        - source/part-2/book-1/chapter-2.qmd
        - source/part-2/book-2/chapter-1.qmd
        - source/part-2/book-2/chapter-2.qmd
    - part: "Luminous Quirk"
      chapters:
        - source/part-3/book-1/chapter-1.qmd
        - source/part-3/book-1/chapter-2.qmd
        - source/part-3/book-2/chapter-1.qmd
        - source/part-3/book-2/chapter-2.qmd
    - part: "Oblique Jubilee"
      chapters:
        - source/part-4/book-1/chapter-1.qmd
        - source/part-4/book-1/chapter-2.qmd
        - source/part-4/book-2/chapter-1.qmd
        - source/part-4/book-2/chapter-2.qmd
  appendices:
    - source/appendices/appendix-a.qmd
    - source/appendices/appendix-b.qmd

format:
  html:
    toc: true
    lof: true
    output-dir: output/html
    css: styles.css
  pdf:
    toc: true
    lof: true
    output-dir: output/pdf
    documentclass: book
