project:
  type: book

book:
  title: "Appendices"
  subtitle: "Measurement, Abstraction, and Information in the Natural World"
  author:
    - name: "Prometheus"
      role: "lead author"
    - name: "Epimetheus"
      role: "co-author"
  chapters:
    - index.qmd
    - source/sample-proofs.qmd
    - source/additional-proofs.qmd

format:
  html:
    toc: true
    lof: true
    css: ../../styles.css
