project:
  type: book

book:
  title: "Oblique Jubilee"
  subtitle: "Measurement, Abstraction, and Information in the Natural World"
  author:
    - name: "Prometheus"
      role: "lead author"
    - name: "Epimetheus"
      role: "co-author"
  chapters:
    - index.qmd
    - frontmatter/how-to-read.qmd
    - part: "Rustic Nebula"
      chapters:
        - source/rustic-nebula/whimsical-barricade.qmd
        - source/rustic-nebula/amber-gyre.qmd
    - part: "Saffron Riddle"
      chapters:
        - source/saffron-riddle/lucid-harpoon.qmd
        - source/saffron-riddle/jubilant-citadel.qmd

format:
  html:
    toc: true
    lof: true
    css: ../../styles.css
